name: Setup

permissions:
  packages: write
  contents: read

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to setup
        required: true
        default: "production"
        type: choice
        options:
          - production

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    timeout-minutes: 15
    environment: ${{ github.event.inputs.environment }}
    concurrency:
      group: deploy_${{ github.event.inputs.environment }}
      cancel-in-progress: false
    env:
      KAMAL_REGISTRY_USERNAME: ${{ secrets.KAMAL_REGISTRY_USERNAME }}
      KAMAL_REGISTRY_PASSWORD: ${{ secrets.KAMAL_REGISTRY_PASSWORD }}
      MARIADB_DATABASE: ${{ secrets.MARIADB_DATABASE }}
      MARIADB_USER: ${{ secrets.MARIADB_USER }}
      MARIADB_PASSWORD: ${{ secrets.MARIADB_PASSWORD }}
      UPTIME_KUMA_DB_NAME: ${{ secrets.MARIADB_DATABASE }}
      UPTIME_KUMA_DB_USERNAME: ${{ secrets.MARIADB_USER }}
      UPTIME_KUMA_DB_PASSWORD: ${{ secrets.MARIADB_PASSWORD }}
    steps:
      - uses: actions/checkout@v4

      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - uses: ruby/setup-ruby@v1
        env:
          BUNDLE_GEMFILE: ./Gemfile
        with:
          ruby-version: mise.toml
          bundler-cache: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Kamal Setup
        run: |
          ./bin/kamal setup -v --destination=${{ github.event.inputs.environment }}

      - name: Kamal Release
        if: ${{ cancelled() || failure() }}
        run: |
          ./bin/kamal lock release --destination=${{ github.event.inputs.environment }}
